US Reverse geocoding API added to SDK.
smartystreets/smartystreets-java-sdk pull request #14
Opened 2020-09-16 22:20 UTC by DuncanBeutler

2020-09-16 23:26 UTC, mdwhatcott requested changes
The main thing is to NOT publish any fields that are deprecated (such as coordinate and address fields at the top-level).

2020-09-16 23:26 UTC, mdwhatcott commented on src/main/java/com/smartystreets/api/us_reverse_geo/Result.java
> +    private double latitude;
Remove this field from the Result class. It should only be provided on the Coordinate class

2020-09-16 23:26 UTC, mdwhatcott commented on src/main/java/com/smartystreets/api/us_reverse_geo/Result.java
> +    private double longitude;
Remove this field from the Result class. It should only be provided on the Coordinate class

2020-09-16 23:26 UTC, mdwhatcott commented on src/main/java/com/smartystreets/api/us_reverse_geo/Result.java
> +    private String street;
Remove this field from the Result class. It should only be provided on the Address class

2020-09-16 23:26 UTC, mdwhatcott commented on src/main/java/com/smartystreets/api/us_reverse_geo/Result.java
> +    private String city;
Remove this field from the Result class. It should only be provided on the Address class

2020-09-16 23:26 UTC, mdwhatcott commented on src/main/java/com/smartystreets/api/us_reverse_geo/Result.java
> +    private String stateAbbreviation;
Remove this field from the Result class. It should only be provided on the Address class

2020-09-16 23:26 UTC, mdwhatcott commented on src/main/java/com/smartystreets/api/us_reverse_geo/Result.java
> +    private String zipcode;
Remove this field from the Result class. It should only be provided on the Address class

2020-09-16 23:26 UTC, mdwhatcott commented on src/main/java/examples/UsReverseGeoExample.java
> +            System.out.println("Latitude: " + result.getLatitude().toString());
Use `result.getCoordinate().getLatitude()`, etc...

2020-09-16 23:26 UTC, mdwhatcott commented on src/test/java/com/smartystreets/api/us_reverse_geo/ClientTest.java
> +        Lookup lookup = new Lookup(44.444444444, -111.111111111);
I propose one of these values be something like `44.888888888` so we see it properly round up in the assertion.

2020-09-17 17:36 UTC, mdwhatcott approved these changes

2020-09-17 17:38 UTC, merged

2020-10-05 23:58 UTC, smccormickescreenlogic commented
What version of the SDK will this be available in? I don't see it in 3.6.1. Or am I doing something wrong?

2020-10-06 00:38 UTC, DuncanBeutler commented
It will be on 3.7.0. It will be along shortly, thank you for asking - we will keep you updated.

2020-10-06 00:47 UTC, DuncanBeutler commented
3.7.0 is available

2020-10-06 00:54 UTC, smccormickescreenlogic commented
Thanks! Saves me switching to an HTTP call.
________________________________
From: Duncan Beutler <notifications@github.com>
Sent: Monday, October 5, 2020 5:47 PM
To: smartystreets/smartystreets-java-sdk <smartystreets-java-sdk@noreply.github.com>
Cc: Steve McCormick <s.mccormick@escreenlogic.com>; Comment <comment@noreply.github.com>
Subject: Re: [External] [smartystreets/smartystreets-java-sdk] US Reverse Geocoding API added to SDK (#14)


3.7.0 is available

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_smartystreets_smartystreets-2Djava-2Dsdk_pull_14-23issuecomment-2D703964993&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=3R6rprrSBzL8v-xrMiRa2UZg41dOQ89xdrDja2JTvBI&m=hgR6SjrXkwxbSk1oLSHgJUNvu8tu0_JyFUZ1_rWUw2Q&s=9FEx__qIDdUC75K0msr5lL2EMiY0rCs2FEN-Hlrhm6Y&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOXGKYEJZ4QKIDG555DBIH3SJJSKTANCNFSM4RPPV76Q&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=3R6rprrSBzL8v-xrMiRa2UZg41dOQ89xdrDja2JTvBI&m=hgR6SjrXkwxbSk1oLSHgJUNvu8tu0_JyFUZ1_rWUw2Q&s=O9V5ntpBGhD1ZlP-l6b1YcLCHBAY_IdESKtREslJowc&e=>.